### ISSUE TITLE
How hard is to adapt the code to aesgcm?

### ISSUE THREAD

**Issue by ekalchev** [tpeczek/Lib.Net.Http.EncryptedContentEncoding#11]
I am working with push notification service that send me a byte[] encrypted with Encrypted Content-Encoding aesgcm. I can see you have implementation of ase128gcm and I want to adapt the code for my needs. Any hint on how to do that?

**Comment by tpeczek** [comment]
In general it shouldn't require any adaption, in fact I'm using this library in my own Push Service client (https://github.com/tpeczek/Lib.Net.Http.WebPush). That push service client is handling the opposite part of communication (sending to Push Service) but this library handles both encoding and decoding. Below is simple decode snippet:

```cs
 byte[] contentToDecode = ...;

 using (MemoryStream source = new MemoryStream(contentToDecode))
 {
     using (MemoryStream destination = new MemoryStream())
     {
         await Aes128GcmEncoding.DecodeAsync(source, destination, KeyProvider);
         byte[] decodedContent = destination.ToArray();
     }
}
```

The only challenge is that KeyProvider implementation.

```
byte[] KeyProvider(byte[] keyId)
{
    ...
}
```

In case of push notification services that `keyId` is usually public key which you can use together with previously exchanged keys for subscription to calculate ECDH agreement. If you provide me with sample data I can help with that in spare moment.

**Comment by ekalchev** [comment]
What I am trying to do is to create C# .net port of https://github.com/MatthieuLemoine/push-receiver
More details here https://medium.com/@MatthieuLemoine/my-journey-to-bring-web-push-support-to-node-and-electron-ce70eea1c0b0. Currently there is no way to do receive Push Notification from Google FCM with .Net C# and I am planning to make this public for the community.

I got everything wired except the final step of decrypting the actual FCM message. The data below is taken with debugger from nodejs code and I can see nodejs crypto use this data to produce the actual decrypted message. Decryption is done here in nodejs code https://github.com/MatthieuLemoine/push-receiver/blob/master/src/utils/decrypt/index.js

"{from: '550920961559', priority: 'normal'}" or bytes

[123, 34, 102, 114, 111, 109, 34, 58, 34, 53, 53, 48, 57, 50, 48, 57, 54, 49, 53, 53, 57, 34, 44, 34, 112, 114, 105, 111, 114, 105, 116, 121, 34, 58, 34, 110, 111, 114, 109, 97, 108, 34, 125]

This below is actual data captured with debugger from nodejs code
```
            ////// generated on the client - ECDH with curve prime256v1//////
            // random bytes
            var authSecret = new byte[] { 5, 47, 48, 155, 244, 31, 204, 235, 11, 247, 67, 120, 24, 137, 25, 153 };

            // public key sent to the server
            var receiverPublicKey = new byte[] { 4, 234, 243, 178, 1, 91, 224, 122, 211, 185, 63, 90, 135, 90, 206, 224, 43, 63, 63, 131, 227, 22, 157, 108, 31, 176, 83, 27, 70, 246, 89, 112, 7, 102, 79, 42, 205, 17, 100, 100, 149, 198, 135, 95, 241, 189, 182, 61, 103, 161, 4, 244, 127, 185, 128, 18, 139, 78, 3, 169, 111, 218, 80, 73, 55};

            // private key kept on the client
            var privateKey = new byte[] { 250, 117, 42, 156, 20, 153, 20, 193, 233, 136, 185, 246, 56, 52, 250, 150, 120, 250, 72, 147, 182, 144, 120, 103, 76, 11, 175, 143, 92, 1, 177, 59 };

            // received from the server
            var salt = new byte[] { 248, 70, 134, 75, 160, 188, 58, 83, 105, 238, 59, 171, 27, 115, 224, 200 };

            // server public key
            var senderPublicKey = new byte[] { 4, 26, 9, 166, 16, 222, 177, 154, 230, 15, 231, 11, 89, 108, 66, 97, 247, 3, 158, 199, 93, 98, 187, 162, 175, 76, 127, 2, 149, 67, 13, 195, 26, 145, 46, 223, 4, 34, 46, 70, 57, 0, 98, 139, 79, 25, 84, 187, 176, 126, 50, 108, 192, 61, 207, 83, 248, 189, 14, 10, 182, 18, 141, 52, 92 };

            // actual data that needs decoding
            var rawData = new byte[] { 127, 5, 92, 210, 222, 94, 48, 180, 122, 71, 186, 120, 91, 171, 10, 6, 14, 182, 145, 108, 136, 161, 172, 8, 67, 27, 136, 55, 6, 224, 180, 181, 141, 242, 21, 101, 235, 6, 125, 162, 97, 236, 49, 150, 61, 225, 130, 58, 57, 93, 37, 79, 208, 21, 8, 139, 72, 235, 12, 173, 50};

**Comment by ekalchev** [comment]
I noticed the keyInfo and nonce info are generation is different for aesgcm and aes128gcm, in nodejs http_ece library. Probably more changes will be needed in your code.

![image](https://user-images.githubusercontent.com/10009149/101953501-21870f80-3c03-11eb-8528-d066112ba7fa.png)

**Comment by tpeczek** [comment]
So I did some more digging and indeed *aesgcm* is from an old draft version of specification (https://tools.ietf.org/html/draft-ietf-httpbis-encryption-encoding-01) and the fact that FCM uses it kinda suprised me. It also looks like FCM has some specific assumptions on how to interpret it.

I could investigate and attempt to provide support, but I would need to have a code which would allow me to test against live data. Otherwise I will almost certainly get it wrong.

**Comment by tpeczek** [comment]
Also I may be able to pull this off provided the entire parsed representation of *kDataMessageStanzaTag* `object` and `_credentials.keys`.

**Comment by ekalchev** [comment]
I was able to port most of the code from http_ece library and I verified I am getting expected results as byte[]

https://gist.github.com/ekalchev/d1286bae6a90ef005576c1ef993898f6

**Comment by tpeczek** [comment]
That's good to hear :)

**Comment by ekalchev** [comment]
For those who end up here, looking for FCM AECGCM decrypt as me. Here my working solution.
https://gist.github.com/ekalchev/1a033ef6e02af0319d61ae1d1b19b3dd
It is not optimized. A lot of byte[] copies can be avoided with streams.
